# Generated by Django 2.2.2 on 2019-06-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190619_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='new-product'),
            preserve_default=False,
        ),
    ]
