# Generated by Django 2.2.2 on 2019-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Awesome product for student wreireorwoeoe weorewo ewrsmcxqwwqe qwe qwe qwewqewqewqeq qweww'),
            preserve_default=False,
        ),
    ]
